version: '3'
services:

  redis:
    image: redis:alpine

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    links:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - job
    links:
      - job

  job:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: pipenv run celery -A manage.celery worker
    depends_on:
      - redis
    links:
      - redis

  test-small:
    build:
      context: .
      dockerfile: ./docker/test-small/Dockerfile

  test-medium:
    build:
      context: .
      dockerfile: ./docker/test-medium/Dockerfile
    depends_on:
      - job
    links:
      - job

  test-large:
    build:
      context: .
      dockerfile: ./docker/test-large/Dockerfile
    depends_on:
      - web
    links:
      - web
    environment:
      WEB_DOMAIN: web:80
