version: '3'
services:

  redis:
    image: redis:alpine

  web:
    image: zyongqing/flask-ci-demo-web:latest
    ports:
      - "80:80"
    links:
      - app

  app:
    image: zyongqing/flask-ci-demo-app:latest
    links:
      - redis
      - job

  job:
    image: zyongqing/flask-ci-demo-app:latest
    command: celery -A manage.celery worker
    links:
      - redis
