version: '3'
services:

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "80:80"
    links:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile

  test:
    build:
      context: .
      dockerfile: ./docker/test/Dockerfile
