version: '3'
services:

  redis:
    image: redis:alpine

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "80:80"
    links:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    links:
      - redis
      - job

  job:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: celery -A manage.celery worker
    links:
      - redis

  test:
    build:
      context: .
      dockerfile: ./docker/test/Dockerfile
    links:
      - redis
