version: '3'
services:

  redis:
    image: redis:alpine

  web:
    image: zyongqing/flask-ci-demo-web:latest
    ports:
      - "80:80"
    depends_on:
      - app
    links:
      - app

  app:
    image: zyongqing/flask-ci-demo-app:latest
    depends_on:
      - job
    links:
      - job

  job:
    image: zyongqing/flask-ci-demo-app:latest
    command: pipenv run celery -A manage.celery worker
    depends_on:
      - redis
    links:
      - redis
